Mvc5_ImageGallery/Models/ImageGalleryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mvc5_ImageGallery.Models
{
    public class ImageGalleryViewModel
    {
        public int ImageID { get; set; }
        public int ImageSize { get; set; }
        public string FileName { get; set; }
        public byte[] ImageData { get; set; }

    }
}

Mvc5_ImageGallery/Controllers/ImageGalleryController.cs
using Mvc5_ImageGallery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc5_ImageGallery.Controllers
{
    public class ImageGalleryController : Controller
    {
        private ImageGalleryContext dbcontext = new ImageGalleryContext();

        // GET: ImageGallery
        public ActionResult Index()
        {
            var image = dbcontext.ImageGalleries.Select(i => new
            {
                i.ImageID,
                i.ImageSize,
                i.FileName,
                i.ImageData
            });

            List<ImageGalleryViewModel> imageViewModel = image.Select(iv => new ImageGalleryViewModel()
            {
                ImageID = iv.ImageID,
                ImageSize = iv.ImageSize,
                FileName = iv.FileName,
                ImageData = iv.ImageData
            }).ToList();

            return View(imageViewModel);
        }

        public ActionResult RetrieveImage(int id)
        {
            //var q = from c in dbcontext.ImageGalleries where c.ImageID == id select c.ImageData;
            var q = dbcontext.ImageGalleries.Where(c => c.ImageID == id).Select(c => c.ImageData);
            byte[] cover = q.First();

            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        public ActionResult Gallery()
        {
            List<ImageGallery> all = new List<ImageGallery>();
            using (ImageGalleryContext context = new ImageGalleryContext())
            {
                all = context.ImageGalleries.ToList();
            }

            return View(all);
        }

        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Upload(ImageGallery image)
        {
            if (image.File.ContentLength > (2 * 1024 * 1024))
            {
                ModelState.AddModelError("CustomError", "File size must be less than 2 MB");
                return View(image);
            }
            if (!(image.File.ContentType == "image/jpeg" || image.File.ContentType == "image/png"))
            {
                ModelState.AddModelError("CustomError", "File type allowed : jpg and png");
                return View();
            }
            image.FileName = image.File.FileName;
            image.ImageSize = image.File.ContentLength;

            byte[] data = new byte[image.File.ContentLength];
            image.File.InputStream.Read(data, 0, image.File.ContentLength);

            image.ImageData = data;
            using (ImageGalleryContext context = new ImageGalleryContext())
            {
                context.ImageGalleries.Add(image);
                context.SaveChanges();
            }

            return RedirectToAction("Gallery");
        }
    }
}

Mvc5_ImageGallery/Views/ImageGallery/Gallery.cshtml
@model List<Mvc5_ImageGallery.ImageGallery>

@{
    ViewBag.Title = "Gallery";
}

<h2>Gallery</h2>

<p>
    @Html.ActionLink("Upload New", "Upload")
</p>
<table class="table">

    @{
        int j = 0;
        for (int i = 0; i < Model.Count(); i += 4)
        {
            j = 1;
            <tr>
                @while (j < i + 4 && j < Model.Count())
                {
                    <td>
                        <img src="data:image/png;base64, @Convert.ToBase64String(Model[j].ImageData, 0, Model[j].ImageData.Length)" width="100"/>
                    </td>
                    j++;
                }
            </tr>
        }
    }

    @*<tr>
                <th>
                    @Html.DisplayNameFor(model => model.ImageID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageSize)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FileName)
                </th>
                <th></th>
            </tr>

        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ImageID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ImageSize)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FileName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }*@

</table>

Mvc5_ImageGallery/Views/ImageGallery/Index.cshtml
@model List<Mvc5_ImageGallery.Models.ImageGalleryViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            <b>Image ID</b>
        </th>
        <th>
            <b>Image Size</b>
        </th>
        <th>
            <b>File Name</b>
        </th>
        <th>
            <b>Image</b>
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ImageID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImageSize)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileName)
        </td>
        <td>
            <img src="/ImageGallery/RetrieveImage/@item.ImageID" alt="" height="100" width="200" /> 
            @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
        </td>
    </tr>
}

</table>

Mvc5_ImageGallery/Views/ImageGallery/Upload.cshtml
@model Mvc5_ImageGallery.ImageGallery

@{
    ViewBag.Title = "Upload";
}

<h2>Upload</h2>
@using (Html.BeginForm("Upload", "ImageGallery", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <table>
        <tr>
            <td>Select File : </td>
            <td>
                @Html.TextBoxFor(Model => Model.File, new { type="file"})
                @Html.ValidationMessage("CustomError")
            </td>
            <td>
                <input type="submit" value="Upload" />
            </td>
        </tr>
    </table>
}
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")    
}