Mvc5_ImageGallery/Controllers/ImageUploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc5_ImageGallery.Controllers
{
    public class ImageUploadController : Controller
    {
        private ImageGalleryContext db = new ImageGalleryContext();

        // GET: ImageUpload
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(FormCollection fc, HttpPostedFileBase file)
        {
            Image image = new Mvc5_ImageGallery.Image();
            var allowedExtensions = new[]
            {
                ".Jpg", ".png", ".jpg", ".jpeg"
            };

            image.ID = Guid.Parse(fc["Id"]);
            image.ImagePath = file.ToString();
            image.Name = fc["Name"].ToString();
            var fileName = Path.GetFileName(file.FileName);
            var ext = Path.GetExtension(file.FileName);

            if (allowedExtensions.Contains(ext))
            {
                string name = Path.GetFileNameWithoutExtension(fileName);
                string myfile = name + "_" + image.ID + ext;
                var path = Path.Combine(Server.MapPath("~/Img"), myfile);
                image.ImagePath = path;
                db.Images.Add(image);
                db.SaveChanges();
                file.SaveAs(path);
            }else
            {
                ViewBag.message = "Please choose only Image file";
            }
            return View();
        }
    }
}

Mvc5_ImageGallery/Views/ImageUpload/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using(Html.BeginForm("Index", "ImageUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        <img id="user_img" height="100" width="90" style="border:solid" />
    </div>

    <div>
        <input type="file" title="search image" id="file" name="file" onchange="show(this)" />
    </div>

    <div>
        UserId
    </div>
    <div>
        <input type="text" id="txt_id" name="id" />
    </div>
    <div>
        UserName
    </div>
    <div>
        <input type="text" id="txt_name" name="Name" />
    </div>
    <input type="submit" title="save" />
}

@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.js"></script>
    <script>
        function show(input) {
            console.log(input);
            if (input.files && input.files[0]) {
                var filedr = new FileReader();
                filedr.onload = function (e) {
                    $('#user_img').attr('src', e.target.result);
                }
                filedr.readAsDataURL(input.files[0]);
            }
        }
    </script>    
}